# Generated by Django 5.0 on 2023-12-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0010_temp_chunked_biginteger'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedupload',
            name='mime_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='storedupload',
            name='original_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storedupload',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temporaryupload',
            name='mime_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='temporaryupload',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
